import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import ImgCarousel from "../components/ImgCarousel";
import AnimeCard from "../components/cards/AnimeCard";
import axios from "axios";
import getSeason from "../utils/getSeason";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import MangaIndexCard from "../components/cards/MangaIndexCard";
import type { GetStaticProps } from "next";
import type { JikanAnime, MangadexManga, Quote } from "../types";

interface HomeProps {
  animes: JikanAnime[];
  manga: MangadexManga[];
  quote: Quote;
  season: JikanAnime[];
}

const Home = ({ animes, manga, quote, season }: HomeProps) => {
  const [animeList, setAnimes] = useState<JikanAnime[]>([]);
  const [mangaList, setManga] = useState<MangadexManga[]>([]);
  const [carousel, setCarousel] = useState<JikanAnime[]>([]);
  const [seasonAnimes, setSeasonAnimes] = useState<JikanAnime[]>([]);

  const populate = () => {
    setAnimes(animes);
    setSeasonAnimes(season);
    setManga(manga);
    setCarousel(animes.slice(0, 3));
  };

  useEffect(() => {
    if (!animeList[1]) {
      populate();
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>AniWorld</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          <section className={styles.quote}>
            <p style={{ fontSize: "large", fontWeight: "bolder" }}>
              {quote.anime.name}
            </p>
            <p data-testid="quote" style={{ fontStyle: "italic" }}>
              &ldquo;{quote.content}&rdquo;
            </p>
            <p style={{ fontStyle: "italic", marginBottom: 0 }}>
              &mdash; {quote.character.name}
            </p>
          </section>
        </Row>
        <Row xs={1} sm={1} md={2}>
          <Col style={{ marginBottom: "5%", marginTop: "4%" }}>
            <ImgCarousel carousel={carousel} />
            <div style={{ marginLeft: "5%", width: "90%", marginTop: "1.5rem" }}>
              <h4 className={styles.sectionHeading}>Season Animes</h4>
              {seasonAnimes.slice(3, 11).map((anime, i) => {
                const destructureDate = anime.aired.prop.from;
                const date = `${destructureDate.month}/${destructureDate.day}/${destructureDate.year}`;
                return (
                  <AnimeCard
                    key={i}
                    name={anime.title}
                    image={anime.images.jpg.image_url}
                    id={anime.mal_id}
                    date={date}
                  />
                );
              })}
            </div>
          </Col>
          <Col style={{ marginBottom: "10%", marginTop: "4%" }}>
            <h4 className={styles.sectionHeading}>Top Recommended</h4>
            {animeList.slice(4, 9).map((anime, i) => {
              const destructureDate = anime.aired.prop.from;
              const date = `${destructureDate.month}/${destructureDate.day}/${destructureDate.year}`;
              return (
                <AnimeCard
                  key={i}
                  name={anime.title}
                  image={anime.images.jpg.image_url}
                  id={anime.mal_id}
                  date={date}
                />
              );
            })}
            <h4 className={styles.sectionHeading} style={{ marginTop: "4%" }}>Top Manga</h4>
            {mangaList?.map((man, i) => (
              <MangaIndexCard
                key={i}
                att={man.attributes}
                id={man.id}
                relationships={man.relationships}
              />
            ))}
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default Home;

const defaultQuote: Quote = {
  content:
    "In this world, evil can arise from the best of intentions. And there is good which can come from evil intentions.",
  anime: {
    id: 456,
    name: "Code Geass: Lelouch of the Rebellion",
    altName: "Code Geass: Hangyaku no Lelouch",
  },
  character: { id: 689, name: "C.C." },
};

export const getStaticProps: GetStaticProps = async () => {
  const date = new Date();
  const season = getSeason(date.getMonth());
  const client = axios.create({ baseURL: "https://api.mangadex.org/" });

  const res = await fetch("https://api.jikan.moe/v4/top/anime");
  const mangaRes = await client.get(
    "manga?limit=4&includes[]=cover_art&originalLanguage[]=en&availableTranslatedLanguage[]=en"
  );
  const Quote = await fetch("https://api.animechan.io/v1/quotes/random");
  const seasonAnimes = await fetch(
    `https://api.jikan.moe/v4/seasons/${date.getFullYear()}/${season}`
  );

  const quoteJson = await Quote?.json();
  const seasonJson = await seasonAnimes.json();
  const data = await res.json();

  return {
    props: {
      animes: data.data,
      manga: mangaRes.data.data,
      quote: quoteJson?.data || defaultQuote,
      season: seasonJson.data,
    },
    revalidate: 3600,
  };
};
