import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import axios from "axios";
import getSeason from "../utils/getSeason";
import type { GetStaticProps } from "next";
import type { JikanAnime, MangadexManga, Quote } from "../types";

interface HomeProps {
  animes: JikanAnime[];
  manga: MangadexManga[];
  quote: Quote;
  season: JikanAnime[];
}

const Home = ({ animes, manga, quote, season }: HomeProps) => {
  const [animeList, setAnimes] = useState<JikanAnime[]>([]);
  const [mangaList, setManga] = useState<MangadexManga[]>([]);
  const [seasonAnimes, setSeasonAnimes] = useState<JikanAnime[]>([]);

  useEffect(() => {
    setAnimes(animes);
    setSeasonAnimes(season);
    setManga(manga);
  }, []);

  const hero = animeList[0];

  const formatDate = (anime: JikanAnime) => {
    const d = anime.aired.prop.from;
    return d.year ? `${d.month}/${d.day}/${d.year}` : "";
  };

  const getMangaCover = (man: MangadexManga): string | null => {
    const rel = man.relationships.find((r) => r.type === "cover_art");
    const fileName = rel?.attributes?.fileName as string | undefined;
    return fileName
      ? `https://uploads.mangadex.org/covers/${man.id}/${fileName}.512.jpg`
      : null;
  };

  const getMangaTitle = (man: MangadexManga): string =>
    man.attributes.title.en || Object.values(man.attributes.title)[0] || "";

  return (
    <div className={styles.container}>
      <Head>
        <title>AniWorld</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ── Hero ── */}
      {hero && (
        <section
          className={styles.hero}
          style={{ backgroundImage: `url(${hero.images.jpg.large_image_url})` }}
        >
          <div className={styles.heroOverlay}>
            <div className={styles.heroContent}>
              <div className={styles.heroBadges}>
                {hero.score && (
                  <span className={`${styles.heroBadge} ${styles.heroScore}`}>
                    ★ {hero.score.toFixed(1)}
                  </span>
                )}
                {hero.rated && (
                  <span className={styles.heroBadge}>{hero.rated}</span>
                )}
                {hero.episodes && (
                  <span className={styles.heroBadge}>{hero.episodes} eps</span>
                )}
              </div>
              <h1 className={styles.heroTitle}>{hero.title}</h1>
              {hero.synopsis && (
                <p className={styles.heroSynopsis}>{hero.synopsis}</p>
              )}
              <Link href={`/anime/${hero.mal_id}`} className={styles.heroBtn}>
                ▶ View Details
              </Link>
            </div>
          </div>
        </section>
      )}

      <div className={styles.sections}>
        {/* ── Top Recommended ── */}
        <section className={styles.section}>
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionHeading}>Top Recommended</h2>
          </div>
          <div className={styles.scrollRow}>
            {animeList.slice(1, 25).map((anime, i) => (
              <Link
                key={i}
                href={`/anime/${anime.mal_id}`}
                className={styles.posterLink}
              >
                <div className={styles.posterCard}>
                  <div className={styles.posterImgWrap}>
                    <Image
                      src={anime.images.jpg.image_url}
                      alt={anime.title}
                      fill
                      style={{ objectFit: "cover" }}
                    />
                  </div>
                  <div className={styles.posterInfo}>
                    <p className={styles.posterTitle}>{anime.title}</p>
                    {anime.score && (
                      <p className={styles.posterMeta}>
                        ★ {anime.score.toFixed(1)}
                      </p>
                    )}
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* ── This Season ── */}
        <section className={styles.section}>
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionHeading}>This Season</h2>
          </div>
          <div className={styles.scrollRow}>
            {seasonAnimes.slice(0, 25).map((anime, i) => (
              <Link
                key={i}
                href={`/anime/${anime.mal_id}`}
                className={styles.posterLink}
              >
                <div className={styles.posterCard}>
                  <div className={styles.posterImgWrap}>
                    <Image
                      src={anime.images.jpg.image_url}
                      alt={anime.title}
                      fill
                      style={{ objectFit: "cover" }}
                    />
                  </div>
                  <div className={styles.posterInfo}>
                    <p className={styles.posterTitle}>{anime.title}</p>
                    <p className={styles.posterMeta}>{formatDate(anime)}</p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* ── Top Manga ── */}
        <section className={styles.section}>
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionHeading}>Top Manga</h2>
          </div>
          <div className={styles.scrollRow}>
            {mangaList.map((man, i) => {
              const cover = getMangaCover(man);
              const title = getMangaTitle(man);
              return (
                <Link
                  key={i}
                  href={`/manga/${man.id}`}
                  className={styles.posterLink}
                >
                  <div className={styles.posterCard}>
                    <div className={styles.posterImgWrap}>
                      {cover && (
                        <Image
                          src={cover}
                          alt={title}
                          fill
                          style={{ objectFit: "cover" }}
                        />
                      )}
                    </div>
                    <div className={styles.posterInfo}>
                      <p className={styles.posterTitle}>{title}</p>
                      <p className={styles.posterMeta}>
                        {man.attributes.status}
                      </p>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        </section>

        {/* ── Quote ── */}
        <section className={styles.quote}>
          <p className={styles.quoteAnime}>{quote.anime.name}</p>
          <p data-testid="quote" className={styles.quoteText}>
            &ldquo;{quote.content}&rdquo;
          </p>
          <p className={styles.quoteChar}>&mdash; {quote.character.name}</p>
        </section>
      </div>
    </div>
  );
};

export default Home;

const defaultQuote: Quote = {
  content:
    "In this world, evil can arise from the best of intentions. And there is good which can come from evil intentions.",
  anime: {
    id: 456,
    name: "Code Geass: Lelouch of the Rebellion",
    altName: "Code Geass: Hangyaku no Lelouch",
  },
  character: { id: 689, name: "C.C." },
};

export const getStaticProps: GetStaticProps = async () => {
  const date = new Date();
  const season = getSeason(date.getMonth());
  const client = axios.create({ baseURL: "https://api.mangadex.org/" });

  const res = await fetch("https://api.jikan.moe/v4/top/anime");
  const mangaRes = await client.get(
    "manga?limit=8&includes[]=cover_art&originalLanguage[]=en&availableTranslatedLanguage[]=en"
  );
  const Quote = await fetch("https://api.animechan.io/v1/quotes/random");
  const seasonAnimes = await fetch(
    `https://api.jikan.moe/v4/seasons/${date.getFullYear()}/${season}`
  );

  const quoteJson = await Quote?.json();
  const seasonJson = await seasonAnimes.json();
  const data = await res.json();

  return {
    props: {
      animes: data.data,
      manga: mangaRes.data.data,
      quote: quoteJson?.data || defaultQuote,
      season: seasonJson.data,
    },
    revalidate: 3600,
  };
};
